In [1]:
from typing import List, Tuple

In [2]:
import numpy as np
import tensorflow as tf

In [74]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences, to_categorical

In [4]:
pares : List[ Tuple[str, str] ] = [
    ("Hello", "Olá"),
    ("Good morning", "Bom dia"),
    ("Good afternoon", "Boa tarde"),
    ("Good evening", "Boa noite"),
    ("Good night", "Boa noite"),
    ("How are you?", "Como você está?"),
    ("I'm fine, thank you.", "Estou bem, obrigado."),
    ("What's your name?", "Qual é o seu nome?"),
    ("My name is John.", "Meu nome é John."),
    ("Nice to meet you.", "Prazer em conhecê-lo."),
    ("Please", "Por favor"),
    ("Thank you", "Obrigado"),
    ("You're welcome", "De nada"),
    ("Excuse me", "Com licença"),
    ("I'm sorry", "Desculpe"),
    ("Yes", "Sim"),
    ("No", "Não"),
    ("Maybe", "Talvez"),
    ("I don't know", "Eu não sei"),
    ("I understand", "Eu entendo"),
    ("I don't understand", "Eu não entendo"),
    ("Can you help me?", "Você pode me ajudar?"),
    ("Where is the bathroom?", "Onde fica o banheiro?"),
    ("How much does it cost?", "Quanto custa?"),
    ("I would like a coffee.", "Eu gostaria de um café."),
    ("Do you speak English?", "Você fala inglês?"),
    ("I speak a little Portuguese.", "Eu falo um pouco de português."),
    ("What time is it?", "Que horas são?"),
    ("I'm hungry.", "Estou com fome."),
    ("I'm thirsty.", "Estou com sede."),
    ("I'm tired.", "Estou cansado."),
    ("I need a doctor.", "Eu preciso de um médico."),
    ("Call the police!", "Chame a polícia!"),
    ("I love you.", "Eu te amo."),
    ("Congratulations!", "Parabéns!"),
    ("Happy birthday!", "Feliz aniversário!"),
    ("Merry Christmas!", "Feliz Natal!"),
    ("Happy New Year!", "Feliz Ano Novo!"),
    ("Good luck!", "Boa sorte!"),
    ("Have a nice day!", "Tenha um bom dia!"),
    ("See you later.", "Até mais."),
    ("Goodbye", "Adeus"),
    ("What's your phone number?", "Qual é o seu número de telefone?"),
    ("Where do you live?", "Onde você mora?"),
    ("I live in São Paulo.", "Eu moro em São Paulo."),
    ("I'm from Brazil.", "Eu sou do Brasil."),
    ("What do you do?", "O que você faz?"),
    ("I'm a teacher.", "Eu sou professor."),
    ("I work in an office.", "Eu trabalho em um escritório."),
    ("I'm a student.", "Eu sou estudante."),
    ("I like to read books.", "Eu gosto de ler livros."),
    ("I enjoy listening to music.", "Eu gosto de ouvir música."),
    ("I like to travel.", "Eu gosto de viajar."),
    ("What's your favorite food?", "Qual é a sua comida favorita?"),
    ("I like pizza.", "Eu gosto de pizza."),
    ("Do you have any pets?", "Você tem animais de estimação?"),
    ("I have a dog.", "Eu tenho um cachorro."),
    ("I don't have any pets.", "Eu não tenho animais de estimação."),
    ("What's your favorite color?", "Qual é a sua cor favorita?"),
    ("My favorite color is blue.", "Minha cor favorita é azul."),
    ("Do you like sports?", "Você gosta de esportes?"),
    ("I like soccer.", "Eu gosto de futebol."),
    ("I don't like sports.", "Eu não gosto de esportes."),
    ("What did you do yesterday?", "O que você fez ontem?"),
    ("I went to the movies.", "Eu fui ao cinema."),
    ("I stayed at home.", "Eu fiquei em casa."),
    ("What are you doing now?", "O que você está fazendo agora?"),
    ("I'm studying English.", "Estou estudando inglês."),
    ("I'm watching TV.", "Estou assistindo TV."),
    ("Do you have brothers or sisters?", "Você tem irmãos ou irmãs?"),
    ("I have one brother.", "Eu tenho um irmão."),
    ("I have two sisters.", "Eu tenho duas irmãs."),
    ("I'm an only child.", "Eu sou filho único."),
    ("What time do you wake up?", "A que horas você acorda?"),
    ("I wake up at 7 a.m.", "Eu acordo às 7 da manhã."),
    ("What time do you go to bed?", "A que horas você vai dormir?"),
    ("I go to bed at 10 p.m.", "Eu vou dormir às 10 da noite."),
    ("Do you like to cook?", "Você gosta de cozinhar?"),
    ("Yes, I love cooking.", "Sim, eu adoro cozinhar."),
    ("No, I don't like to cook.", "Não, eu não gosto de cozinhar."),
    ("What's your favorite movie?", "Qual é o seu filme favorito?"),
    ("I like action movies.", "Eu gosto de filmes de ação."),
    ("I prefer comedies.", "Eu prefiro comédias."),
    ("Do you play any instruments?", "Você toca algum instrumento?"),
    ("I play the guitar.", "Eu toco violão."),
    ("I don't play any instruments.", "Eu não toco nenhum instrumento."),
    ("What's the weather like?", "Como está o tempo?"),
    ("It's sunny.", "Está ensolarado."),
    ("It's raining.", "Está chovendo."),
    ("It's cold.", "Está frio."),
    ("It's hot.", "Está quente."),
    ("Do you like reading?", "Você gosta de ler?"),
    ("Yes, I read every day.", "Sim, eu leio todos os dias."),
    ("No, I prefer watching movies.", "Não, eu prefiro assistir filmes."),
    ("What's your favorite book?", "Qual é o seu livro favorito?"),
    ("I like mystery novels.", "Eu gosto de romances de mistério."),
    ("I enjoy science fiction.", "Eu gosto de ficção científica."),
    ("Can you drive?", "Você sabe dirigir?"),
    ("Yes, I have a driver's license.", "Sim, eu tenho carteira de motorista."),
    ("No, I don't drive.", "Não, eu não dirijo."),
    ("Do you like coffee or tea?", "Você gosta de café ou chá?"),
    ("I prefer coffee.", "Eu prefiro café."),
    ("I like both.", "Eu gosto dos dois."),
    ("I don't like either.", "Eu não gosto de nenhum."),
]

In [5]:
textos_ingles : List[str ] = []
textos_portugues : List[ str ] = []

In [6]:
for par in pares:
    textos_ingles.append(par[0])
    textos_portugues.append("<BOS> " + par[1] + " <EOS>")

In [7]:
tokenizer_ingles = Tokenizer()
tokenizer_ingles.fit_on_texts( textos_ingles )
vocabulario_ingles = tokenizer_ingles.word_index

In [8]:
tokenizer_portugues = Tokenizer()
tokenizer_portugues.fit_on_texts( textos_portugues )
vocabulario_portugues = tokenizer_portugues.word_index

In [9]:
sequencias_ingles = tokenizer_ingles.texts_to_sequences( textos_ingles )
print(textos_ingles[0:5])
print(sequencias_ingles[0:5])

['Hello', 'Good morning', 'Good afternoon', 'Good evening', 'Good night']
[[62], [13, 63], [13, 64], [13, 65], [13, 66]]


In [10]:
sequencias_portugues = tokenizer_portugues.texts_to_sequences( textos_portugues )
print(textos_portugues[0:5])
print(sequencias_portugues[0:5])

['<BOS> Olá <EOS>', '<BOS> Bom dia <EOS>', '<BOS> Boa tarde <EOS>', '<BOS> Boa noite <EOS>', '<BOS> Boa noite <EOS>']
[[1, 57, 2], [1, 31, 32, 2], [1, 17, 58, 2], [1, 17, 23, 2], [1, 17, 23, 2]]


In [24]:
maximo_palavras = 0
for seq in sequencias_ingles:
    if len(seq) > maximo_palavras:
        maximo_palavras = len(seq)

for seq in sequencias_portugues:
    if len(seq) > maximo_palavras:
        maximo_palavras = len(seq)
maximo_palavras

9

In [36]:
# x = [[1, 57, 2]]
# pad_sequences( x, maxlen=20, padding="pre" )

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  1, 57,  2]])

In [44]:
encoder_entrada_dados = pad_sequences(sequencias_ingles, maxlen=maximo_palavras, padding="pre")
print(sequencias_ingles[0:3])
print(encoder_entrada_dados[0:3])

[[62], [13, 63], [13, 64]]
[[ 0  0  0  0  0  0  0  0 62]
 [ 0  0  0  0  0  0  0 13 63]
 [ 0  0  0  0  0  0  0 13 64]]


In [58]:
# for seq in sequencias_portugues[0:5]:
#    print(seq[:-1])

# [seq[:-1] for seq in sequencias_portugues]

In [64]:
decoder_entrada_dados = pad_sequences([seq[:-1] for seq in sequencias_portugues], maxlen=maximo_palavras, padding="pre")
print(sequencias_portugues[0:3])
print(decoder_entrada_dados[0:3])
decoder_saida_dados = pad_sequences([seq[1:] for seq in sequencias_portugues], maxlen=maximo_palavras, padding="pre")
print(sequencias_portugues[0:3])
print(decoder_saida_dados[0:3])

[[1, 57, 2], [1, 31, 32, 2], [1, 17, 58, 2]]
[[ 0  0  0  0  0  0  0  1 57]
 [ 0  0  0  0  0  0  1 31 32]
 [ 0  0  0  0  0  0  1 17 58]]
[[1, 57, 2], [1, 31, 32, 2], [1, 17, 58, 2]]
[[ 0  0  0  0  0  0  0 57  2]
 [ 0  0  0  0  0  0 31 32  2]
 [ 0  0  0  0  0  0 17 58  2]]


In [72]:
len(tokenizer_portugues.word_index)


178

In [ ]:
#    0     1       2       3      ...  177
# [0.05, 0.008, 0.0003, 0.0001, ...., 0.07]  # len => 178

In [ ]:
# [ 0  0  0  0  0  0  0 57  2]
#      0  1  2  3  4  5  6  7  ... 57 ... 176 177
# [ 
#     [1, 0, 0, 0, 0, 0, 0, 0 ..........., 0,  0],
#     [1, 0, 0, 0, 0, 0, 0, 0 ..........., 0,  0],
#     [1, 0, 0, 0, 0, 0, 0, 0 ..........., 0,  0],
#     [1, 0, 0, 0, 0, 0, 0, 0 ..........., 0,  0],
#     [1, 0, 0, 0, 0, 0, 0, 0 ..........., 0,  0],
#     [1, 0, 0, 0, 0, 0, 0, 0 ..........., 0,  0],
#     [1, 0, 0, 0, 0, 0, 0, 0 ..........., 0,  0],
#     [0, 0, 0, 0, 0, 0, 0, .....,1, ...., 0,  0],
#     [0, 0, 1, 0, 0, 0, 0, 0 ..........., 0,  0]
# ]

In [82]:
quantidade_classes_dicionario = len(vocabulario_portugues) + 1

In [84]:
decoder_saida_dados_onehot = to_categorical(decoder_saida_dados, num_classes=quantidade_classes_dicionario)
print(decoder_saida_dados[0:2])
print(decoder_saida_dados_onehot[0:2])

[[ 0  0  0  0  0  0  0 57  2]
 [ 0  0  0  0  0  0 31 32  2]]
[[[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]]]
