In [ ]:
#   ! pip install numpy

In [3]:
import numpy as np

In [4]:
matriz1 = [
    [10, 20, 30],
    [40, 50, 60]
]  # Matriz 2 x 3

In [43]:
matriz2 = np.array( matriz1, dtype=np.int8 )
matriz2

array([[10, 20, 30],
       [40, 50, 60]], dtype=int8)

In [47]:
matriz3 = np.array( [254, 128, 127], dtype=np.uint8 )  
matriz3 + 2

array([  0, 130, 129], dtype=uint8)

In [53]:
matriz2.ndim

2

In [55]:
matriz2.shape

(2, 3)

In [57]:
matriz2.dtype

dtype('int8')

In [67]:
matriz_zeros = np.zeros([5, 4])
matriz_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
matriz_uns = np.ones([4, 5])
matriz_uns

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
matriz_eye = np.eye(5)
matriz_eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [75]:
vetor_1_30 = np.arange(1, 30, 0.6)
vetor_1_30

array([ 1. ,  1.6,  2.2,  2.8,  3.4,  4. ,  4.6,  5.2,  5.8,  6.4,  7. ,
        7.6,  8.2,  8.8,  9.4, 10. , 10.6, 11.2, 11.8, 12.4, 13. , 13.6,
       14.2, 14.8, 15.4, 16. , 16.6, 17.2, 17.8, 18.4, 19. , 19.6, 20.2,
       20.8, 21.4, 22. , 22.6, 23.2, 23.8, 24.4, 25. , 25.6, 26.2, 26.8,
       27.4, 28. , 28.6, 29.2, 29.8])

In [83]:
matriz_concatenada = np.concatenate( [matriz_uns, matriz_eye])
print(matriz_concatenada)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [85]:
matriz_concatenada = np.concatenate( [matriz_zeros, matriz_eye], axis=1 )
matriz_concatenada

array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [97]:
np.zeros_like( matriz_concatenada ) 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [93]:
matriz_concatenada.astype(bool)

array([[False, False, False, False,  True, False, False, False, False],
       [False, False, False, False, False,  True, False, False, False],
       [False, False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False, False,  True]])

In [99]:
np.random.random( [7,5] ) 

array([[0.51329138, 0.84035704, 0.49613473, 0.28743275, 0.3145437 ],
       [0.09780818, 0.73728524, 0.39200705, 0.90893922, 0.64887474],
       [0.26638184, 0.95079145, 0.90651834, 0.76308161, 0.5454314 ],
       [0.09386463, 0.62694553, 0.82960959, 0.98780011, 0.45482505],
       [0.04009618, 0.20095665, 0.54179085, 0.06595998, 0.76226719],
       [0.00530071, 0.37513405, 0.29752482, 0.70727476, 0.86645824],
       [0.19377796, 0.14039887, 0.2222272 , 0.71219119, 0.61672692]])

In [101]:
np.random.randint( 10, 20, [7,5] ) 

array([[11, 13, 19, 13, 11],
       [12, 19, 13, 19, 15],
       [15, 10, 19, 13, 11],
       [12, 14, 16, 12, 16],
       [18, 11, 11, 18, 14],
       [19, 10, 14, 12, 17],
       [19, 19, 15, 12, 18]])