In [ ]:
#   ! pip install numpy

In [3]:
import numpy as np

In [4]:
matriz1 = [
    [10, 20, 30],
    [40, 50, 60]
]  # Matriz 2 x 3

In [43]:
matriz2 = np.array( matriz1, dtype=np.int8 )
matriz2

array([[10, 20, 30],
       [40, 50, 60]], dtype=int8)

In [47]:
matriz3 = np.array( [254, 128, 127], dtype=np.uint8 )  
matriz3 + 2

array([  0, 130, 129], dtype=uint8)

In [53]:
matriz2.ndim

2

In [55]:
matriz2.shape

(2, 3)

In [57]:
matriz2.dtype

dtype('int8')

In [67]:
matriz_zeros = np.zeros([5, 4])
matriz_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
matriz_uns = np.ones([4, 5])
matriz_uns

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
matriz_eye = np.eye(5)
matriz_eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [75]:
vetor_1_30 = np.arange(1, 30, 0.6)
vetor_1_30

array([ 1. ,  1.6,  2.2,  2.8,  3.4,  4. ,  4.6,  5.2,  5.8,  6.4,  7. ,
        7.6,  8.2,  8.8,  9.4, 10. , 10.6, 11.2, 11.8, 12.4, 13. , 13.6,
       14.2, 14.8, 15.4, 16. , 16.6, 17.2, 17.8, 18.4, 19. , 19.6, 20.2,
       20.8, 21.4, 22. , 22.6, 23.2, 23.8, 24.4, 25. , 25.6, 26.2, 26.8,
       27.4, 28. , 28.6, 29.2, 29.8])

In [83]:
matriz_concatenada = np.concatenate( [matriz_uns, matriz_eye])
print(matriz_concatenada)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [85]:
matriz_concatenada = np.concatenate( [matriz_zeros, matriz_eye], axis=1 )
matriz_concatenada

array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [97]:
np.zeros_like( matriz_concatenada ) 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [93]:
matriz_concatenada.astype(bool)

array([[False, False, False, False,  True, False, False, False, False],
       [False, False, False, False, False,  True, False, False, False],
       [False, False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False, False,  True]])

In [99]:
np.random.random( [7,5] ) 

array([[0.51329138, 0.84035704, 0.49613473, 0.28743275, 0.3145437 ],
       [0.09780818, 0.73728524, 0.39200705, 0.90893922, 0.64887474],
       [0.26638184, 0.95079145, 0.90651834, 0.76308161, 0.5454314 ],
       [0.09386463, 0.62694553, 0.82960959, 0.98780011, 0.45482505],
       [0.04009618, 0.20095665, 0.54179085, 0.06595998, 0.76226719],
       [0.00530071, 0.37513405, 0.29752482, 0.70727476, 0.86645824],
       [0.19377796, 0.14039887, 0.2222272 , 0.71219119, 0.61672692]])

In [101]:
np.random.randint( 10, 20, [7,5] ) 

array([[11, 13, 19, 13, 11],
       [12, 19, 13, 19, 15],
       [15, 10, 19, 13, 11],
       [12, 14, 16, 12, 16],
       [18, 11, 11, 18, 14],
       [19, 10, 14, 12, 17],
       [19, 19, 15, 12, 18]])

In [105]:
array1 = np.arange(100, 200, 5)
array1

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195])

In [107]:
array1.shape

(20,)

In [109]:
array1.reshape([4, 5])

array([[100, 105, 110, 115, 120],
       [125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170],
       [175, 180, 185, 190, 195]])

In [119]:
array2 = array1.reshape([5, 2, -1])
array2

array([[[100, 105],
        [110, 115]],

       [[120, 125],
        [130, 135]],

       [[140, 145],
        [150, 155]],

       [[160, 165],
        [170, 175]],

       [[180, 185],
        [190, 195]]])

In [123]:
array2.ravel()

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195])

In [139]:
array3 = array2.copy()
array3

array([[[100, 105],
        [110, 105]],

       [[120, 125],
        [130, 135]],

       [[140, 145],
        [150, 155]],

       [[160, 165],
        [170, 175]],

       [[180, 185],
        [190, 195]]])

In [141]:
array3[0, 1, 1] = 130

In [143]:
array3

array([[[100, 105],
        [110, 130]],

       [[120, 125],
        [130, 135]],

       [[140, 145],
        [150, 155]],

       [[160, 165],
        [170, 175]],

       [[180, 185],
        [190, 195]]])

In [145]:
array2

array([[[100, 105],
        [110, 105]],

       [[120, 125],
        [130, 135]],

       [[140, 145],
        [150, 155]],

       [[160, 165],
        [170, 175]],

       [[180, 185],
        [190, 195]]])

In [147]:
array1

array([100, 105, 110, 105, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195])

In [149]:
array4 = array1.reshape([4, 5])

In [151]:
array4

array([[100, 105, 110, 105, 120],
       [125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170],
       [175, 180, 185, 190, 195]])

In [165]:
# array5 = np.eye(5)
array5 = np.random.randint(2, 8, [4, 5]) 
array5

array([[4, 3, 3, 7, 4],
       [7, 3, 5, 6, 4],
       [7, 3, 2, 6, 7],
       [4, 6, 3, 3, 3]])

In [167]:
np.matmul(array4, array5)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 5)

In [171]:
array4.shape

(4, 5)

In [175]:
array5

array([[4, 3, 3, 7, 4],
       [7, 3, 5, 6, 4],
       [7, 3, 2, 6, 7],
       [4, 6, 3, 3, 3]])

In [191]:
array6 = array5.T
array6

array([[4, 7, 7, 4],
       [3, 3, 3, 6],
       [3, 5, 2, 3],
       [7, 6, 6, 3],
       [4, 4, 7, 3]])

In [193]:
array5.reshape(5, 4)

array([[4, 3, 3, 7],
       [4, 7, 3, 5],
       [6, 4, 7, 3],
       [2, 6, 7, 4],
       [6, 3, 3, 3]])

In [187]:
# (4, 5) X (5, 4)

In [197]:
array7 = np.matmul(array4, array6)
array7

array([[2260, 2675, 2705, 2035],
       [2855, 3360, 3390, 2540],
       [3380, 3985, 4015, 3015],
       [3905, 4610, 4640, 3490]])

In [199]:
np.savez("array_multiplicado.npz", matriz=array7)

In [201]:
arquivo = np.load("array_multiplicado.npz")
array8 = arquivo["matriz"]
array8

array([[2260, 2675, 2705, 2035],
       [2855, 3360, 3390, 2540],
       [3380, 3985, 4015, 3015],
       [3905, 4610, 4640, 3490]])

In [213]:
array8 > 3000

array([[False, False, False, False],
       [False,  True,  True, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [221]:
array8 **= 2

In [223]:
array8

array([[ 5107600,  7155625,  7317025,  4141225],
       [ 8151025, 11289600, 11492100,  6451600],
       [11424400, 15880225, 16120225,  9090225],
       [15249025, 21252100, 21529600, 12180100]])

In [241]:
np.exp(array8 ** (1/10))

array([[108.44133847, 127.3459994 , 128.73176669,  98.39060467],
       [135.70035734, 159.6581494 , 161.10587749, 121.14245149],
       [160.62299328, 190.39671976, 191.90289792, 143.20736025],
       [186.39407504, 222.36254958, 223.92803456, 165.95170224]])

In [263]:
array8[::2, 0:1:1]

array([[ 5107600],
       [11424400]])

In [245]:
array8[:, -1:]

array([[ 4141225],
       [ 6451600],
       [ 9090225],
       [12180100]])

In [249]:
array8[ array8 % 2 == 0  ].reshape(2, -1)

array([[ 5107600, 11289600, 11492100,  6451600],
       [11424400, 21252100, 21529600, 12180100]])

In [265]:
array8

array([[ 5107600,  7155625,  7317025,  4141225],
       [ 8151025, 11289600, 11492100,  6451600],
       [11424400, 15880225, 16120225,  9090225],
       [15249025, 21252100, 21529600, 12180100]])

In [273]:
array8.sum(axis=0)

array([39932050, 55577550, 56458950, 31863150])

In [275]:
 5107600 + 8151025 + 11424400 + 15249025

39932050