In [1]:
import numpy as np 

In [25]:
a = np.array(  [ [10, 20], [30, 40] ], dtype = np.uint8)
a

array([[10, 20],
       [30, 40]], dtype=uint8)

In [27]:
a.dtype

dtype('uint8')

In [46]:
a.shape

(2, 2)

In [34]:
a.ndim

2

In [38]:
b = np.array( [ 
    [ [10, 20], [30, 40] ], 
    [ [50, 60], [70, 80] ], 
    [ [90, 100], [110, 120] ]
])

In [40]:
b.ndim

3

In [42]:
b.dtype

dtype('int32')

In [44]:
b.shape

(3, 2, 2)

In [56]:
z = np.ones([8, 8])
z

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [66]:
faixa = np.arange(0, 10, 0.1)
faixa

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [68]:
faixa1 = np.arange(0, 5, 0.1)
faixa1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [72]:
faixa2 = np.arange(-5, 0, 0.1)
faixa2

array([-5. , -4.9, -4.8, -4.7, -4.6, -4.5, -4.4, -4.3, -4.2, -4.1, -4. ,
       -3.9, -3.8, -3.7, -3.6, -3.5, -3.4, -3.3, -3.2, -3.1, -3. , -2.9,
       -2.8, -2.7, -2.6, -2.5, -2.4, -2.3, -2.2, -2.1, -2. , -1.9, -1.8,
       -1.7, -1.6, -1.5, -1.4, -1.3, -1.2, -1.1, -1. , -0.9, -0.8, -0.7,
       -0.6, -0.5, -0.4, -0.3, -0.2, -0.1])

In [82]:
faixa_total = np.concatenate([faixa2, faixa1])
faixa_total

array([-5. , -4.9, -4.8, -4.7, -4.6, -4.5, -4.4, -4.3, -4.2, -4.1, -4. ,
       -3.9, -3.8, -3.7, -3.6, -3.5, -3.4, -3.3, -3.2, -3.1, -3. , -2.9,
       -2.8, -2.7, -2.6, -2.5, -2.4, -2.3, -2.2, -2.1, -2. , -1.9, -1.8,
       -1.7, -1.6, -1.5, -1.4, -1.3, -1.2, -1.1, -1. , -0.9, -0.8, -0.7,
       -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,
        0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,  1.2,  1.3,  1.4,  1.5,
        1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,
        2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,
        3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,
        4.9])

In [84]:
faixa_total.astype(np.int32)

array([-5, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -3, -3, -3, -3, -3, -3,
       -3, -3, -3, -3, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4])

In [86]:
uns = np.ones([8, 8])
uns

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [94]:
np.zeros_like( faixa_total )

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [108]:
np.random.randint(1, 20, [5,4])

array([[ 8, 10, 10,  2],
       [ 1,  5,  6,  5],
       [16, 17,  4, 10],
       [ 5,  4, 19,  7],
       [16, 17, 11, 17]])

In [110]:
np.random.random([8,8])

array([[5.79296392e-01, 9.31727180e-01, 3.01768902e-01, 3.37228331e-01,
        5.64421390e-01, 8.86997642e-01, 4.37317878e-01, 3.21527506e-01],
       [1.19916139e-01, 4.15682967e-01, 3.81533127e-01, 3.38096927e-02,
        4.16282793e-01, 2.57840245e-01, 1.61597877e-01, 1.88054101e-01],
       [8.98838486e-01, 2.73403148e-01, 6.76349038e-01, 7.48429409e-01,
        3.52984383e-01, 2.33114751e-01, 6.80347067e-01, 9.40672916e-01],
       [5.16022281e-01, 6.38210190e-01, 3.73254758e-04, 8.34709282e-01,
        4.67692602e-02, 1.72355136e-01, 7.60302357e-02, 8.52324730e-01],
       [8.63112723e-01, 8.57414594e-01, 1.40817842e-01, 2.69266477e-01,
        2.21917595e-01, 7.93117134e-01, 2.87011939e-02, 7.22479555e-01],
       [9.17919295e-02, 3.09232493e-01, 1.29550995e-01, 7.39110169e-02,
        5.19597402e-01, 6.15707136e-01, 1.57943695e-01, 2.59002436e-01],
       [5.35500409e-01, 3.78439545e-01, 5.16297008e-02, 4.85968344e-01,
        3.31264089e-01, 7.70784316e-01, 6.68139846e-01, 1.

In [120]:
numeros = np.arange(1, 51)
numeros

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [130]:
numeros.reshape( [-1, 6] ) 

ValueError: cannot reshape array of size 50 into shape (6)

In [132]:
numeros.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [134]:
matriz1 = np.arange(0, 200).reshape([20, -1])
matriz1

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [136]:
matriz1.ravel()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [142]:
matriz2 = matriz1.flatten().copy()
matriz2

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [150]:
matriz_original = np.arange( 0, 100, 10 ).reshape([5, 2])
matriz_original

array([[ 0, 10],
       [20, 30],
       [40, 50],
       [60, 70],
       [80, 90]])

In [152]:
matriz_original.reshape([2, -1])

array([[ 0, 10, 20, 30, 40],
       [50, 60, 70, 80, 90]])

In [154]:
matriz_original.transpose()

array([[ 0, 20, 40, 60, 80],
       [10, 30, 50, 70, 90]])

In [158]:
matriz_transposta = matriz_original.T
matriz_transposta

array([[ 0, 20, 40, 60, 80],
       [10, 30, 50, 70, 90]])

In [160]:
np.savez('matriz.npz', matriz=matriz_transposta)

In [172]:
matriz_carregada = np.load('matriz.npz')["matriz"]
matriz_carregada

array([[ 0, 20, 40, 60, 80],
       [10, 30, 50, 70, 90]])

In [174]:
matriz_original.reshape([2, -1])


array([[ 0, 10, 20, 30, 40],
       [50, 60, 70, 80, 90]])

In [178]:
matriz_carregada * matriz_original.reshape([2, -1])

array([[   0,  200,  800, 1800, 3200],
       [ 500, 1800, 3500, 5600, 8100]])

In [182]:
matriz_carregada

array([[ 0, 20, 40, 60, 80],
       [10, 30, 50, 70, 90]])

In [188]:
matriz_carregada % 3 == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [198]:
copia1 = matriz_carregada.view()
copia1

array([[ 0, 20, 40, 60, 80],
       [10, 30, 50, 70, 90]])

In [200]:
copia1 = copia1 % 3 == 0

In [202]:
copia1

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [204]:
matriz_carregada

array([[ 0, 20, 40, 60, 80],
       [10, 30, 50, 70, 90]])

In [230]:
matriz_carregada/0

C:\Users\anton\AppData\Local\Temp\ipykernel_18688\1881799409.py:1: RuntimeWarning: divide by zero encountered in divide
  matriz_carregada/0
C:\Users\anton\AppData\Local\Temp\ipykernel_18688\1881799409.py:1: RuntimeWarning: invalid value encountered in divide
  matriz_carregada/0


array([[nan, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [242]:
matriz_carregada[:, -2:]

array([[60, 80],
       [70, 90]])

In [258]:
tabuleiro = np.random.randint(1, 10, [8, 8])
tabuleiro

array([[6, 3, 5, 3, 4, 7, 6, 4],
       [8, 8, 5, 9, 1, 9, 6, 3],
       [4, 7, 3, 1, 6, 8, 2, 8],
       [7, 8, 9, 5, 7, 4, 6, 1],
       [8, 4, 9, 4, 4, 9, 7, 5],
       [5, 9, 6, 9, 1, 3, 5, 7],
       [7, 7, 1, 8, 2, 9, 3, 2],
       [8, 1, 8, 8, 9, 3, 3, 6]])

In [264]:
outra_matriz = tabuleiro[1:-1, 1:-1]

In [276]:
outra_matriz[outra_matriz %2 == 0] = 0
outra_matriz

array([[0, 5, 9, 1, 9, 0],
       [7, 3, 1, 0, 0, 0],
       [0, 9, 5, 7, 0, 0],
       [0, 9, 0, 0, 9, 7],
       [9, 0, 9, 1, 3, 5],
       [7, 1, 0, 0, 9, 3]])

In [280]:
outra_matriz[ ::-1, 1 ] 

array([1, 0, 9, 9, 3, 5])

In [296]:
outra_matriz.sum(axis=1)

array([24, 11, 21, 25, 27, 20])

In [298]:
outra_matriz

array([[0, 5, 9, 1, 9, 0],
       [7, 3, 1, 0, 0, 0],
       [0, 9, 5, 7, 0, 0],
       [0, 9, 0, 0, 9, 7],
       [9, 0, 9, 1, 3, 5],
       [7, 1, 0, 0, 9, 3]])

In [302]:
matrix1 = matriz_carregada
matrix1

array([[ 0, 20, 40, 60, 80],
       [10, 30, 50, 70, 90]])

In [320]:
matrix2 = matriz_original.reshape([2, -1])
matrix2.T

array([[ 0, 50],
       [10, 60],
       [20, 70],
       [30, 80],
       [40, 90]])

In [316]:
matrix1.shape

(2, 5)

In [314]:
 matrix2.shape

(2, 5)

In [318]:
np.dot(matrix1, matrix2.T)

array([[ 6000, 16000],
       [ 7000, 19500]])