In [1]:
import tensorflow as tf

In [3]:
a = tf.constant( 10 ) 

In [5]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [7]:
a.shape

TensorShape([])

In [9]:
a.dtype

tf.int32

In [11]:
a.ndim

0

In [13]:
b = tf.Variable( 20 ) 

In [15]:
b

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=20>

In [17]:
c = a * b

In [19]:
c

<tf.Tensor: shape=(), dtype=int32, numpy=200>

In [21]:
d = tf.Variable( [[10, 20, 30], [40, 50, 60]] )

In [23]:
d

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60]])>

In [31]:
d.ndim

AttributeError: 'ResourceVariable' object has no attribute 'ndim'